version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install

      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      - run:
          name: Linting
          command: |
            poetry run pre-commit run --source origin/master --origin HEAD

      - run:
          name: Tests
          command: |
            poetry run true

  deployment:
    docker:
      - image: circleci/python:3.6.8
    steps:
        - checkout
        - run:
            name: Push to PyPI
            command: |
              poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction

workflows:
  version: 2

  build-and-test-workflow:
    jobs:
      - build-and-test

  deployment-workflow:
    jobs:
      # Runs build and test, but now just on Git tags (created from a GitHub release)
      - build-and-test:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      # Runs the deployment job, just with the tags as well
      - deployment:
          requires:
            - build-and-test
          filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/
