version: 2.1

workflows:
  version: 2
  tests-workflow:
    jobs:
      - build
      - test-version:
          version: "3.6"
          requires:
            - build
      - test-version:
          version: "3.7"
          requires:
            - build
      - test-py2:
          requires:
            - build

  deployment-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      - test-version:
          version: "3.6"
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      - deploy:
          requires:
            - test-version
          filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - /home/circleci/.cache/pre-commit
      - run:
          name: Linting
          command: |
            poetry run pre-commit run --source origin/master --origin HEAD

  test-version:
    parameters:
      version:
        type: string
        default: "3.6.8"
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Tests
          command: |
            poetry run true

  test-py2:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-py2-django11-fsm26
      - run:
          name: Install Dependencies
          command: |
            pip install --user django~=1.11
      - save_cache:
          key: deps-py2-django11
          paths:
            - /home/circleci/.cache/pip/
      - run:
          name: Tests
          command: |
            python -c "import django; print(django.get_version())"

  deploy:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name: Push to PyPI
          command: |
            poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction
